### ISSUE TITLE
组织进行一批数据标记

### ISSUE THREAD

**Issue by sg-first** [Goldbach-Research-Group/Orientation-analysis#1]
以snownlp训练集格式标记一批数据：
* 等量的`正常负面反对评论`和`直接支持鼓励评论`
* 等量且较多的`反讽评论`和`对反对者不满的支持者评论`

**Comment by sg-first** [comment]
从答案里按不同区间段（排前面的 中间的 后面的……可以多分几段）自动筛选一些回答 然后导出成csv文件（这样可以用excel打开方便大家标记）这个csv文件（表格）第一列是回答者的token（回头可以知道对应的是json里的哪个回答）第二列是答案内容。然后标记者直接在表格里标记

让标记者用负面嘲讽(0.1) 负面鼓励(0.4) 正面鼓励(0.6) 正面支持(0.9)四个标签对答案做标记

**Comment by sg-first** [comment]
被标记答案的筛选不用太细，支持和反对相差别特别悬殊就行了

因为前面的都是反对的 所以前面少选点 后面支持的多选点

**Comment by MichaelTenma** [comment]
已完成抽样工作，具体文件见(./DataDealer/answersCombine)，尚未转换为csv文件格式，并且文件编码格式异常。
需要解决的问题：
+ + 文件编码问题
+ + 提取纯文本问题
+ + 转换为csv问题

**Comment by sg-first** [comment]
基于MichaelTenma的代码搞定
