### ISSUE TITLE
训练朴素贝叶斯模型

### ISSUE THREAD

**Issue by sg-first** [Goldbach-Research-Group/Orientation-analysis#3]
窝琢磨了一下，还是应该做两手准备，所以贝叶斯模型也应该训练一下。例子什么的我大概都做好了，把他们拼起来就可以了，谢谢！！下面是每一步的行动：

* 把标记的回答数据（就是data里面的[倾向性分析数据集](https://github.com/Goldbach-Research-Group/data/blob/master/%E5%80%BE%E5%90%91%E6%80%A7%E5%88%86%E6%9E%90/%E5%80%BE%E5%90%91%E6%80%A7%E5%88%86%E6%9E%90%E6%95%B0%E6%8D%AE%E9%9B%86.xls)）里的回答搞下来，把标记的回答和其它所有的回答连在一起弄成一个列表，参照[这个例子](https://github.com/Goldbach-Research-Group/Orientation-analysis/blob/master/vector.py)把这些回答用sklearn转换成词向量（ont-hot表示）

* 读入`倾向性分析数据集`里面的评分，与已标记的词向量数据对应，参照[这个例子](https://github.com/Goldbach-Research-Group/Orientation-analysis/blob/master/nb.py)进行训练，然后可以用训练好的模型预测未标记的词向量的评分。这里需要注意，标记不完全是`0.1 0.25 0.75 0.9`四类，有一些是`0.2`，但用贝叶斯做四分类的话那`0.2`就视为`0.1`吧

如果预测结果不够理想，可以用以下方式改进：

* **使用停用词表**：载入停用词表的代码已经写在向量化的例子里了，停用词表[这里](https://github.com/sg-first/SWS-dictionary/blob/master/stopWords/stopWordList(sou).txt)有，直接载入即可

* **使用更少的向量维度**：可能有一些词在每个文档里都出现，所以词向量统计他们没有意义，或者有些词很少有文档出现，统计他们也没有意义，可以在构造`CountVectorizer`的时候使用两个参数指定作为词向量维度的词的DF值区间，大概是如下：
``` python
vect = CountVectorizer(max_df = ……,min_df = ……,stop_words=stpwrdlst)
```

* 例子里写的是高斯贝叶斯，但实际词向量并不是连续的，而且这个多分类问题也更适合多项贝叶斯，也就是把`GaussianNB`改成`MultinomialNB`

祝成功！！

**Comment by sg-first** [comment]
噢，那个步骤再补充一下，把回答都读入做成列表之后要分词，用`jieba`这分词库做就可以，分词之后把每个回答都转换成两个词之间用空格分隔的字符串形式，这样就可以用sklearn那个模块向量化了（例子里大概写了就是那个意思

**Comment by tootal** [comment]
[尝试弄了一下](https://github.com/Goldbach-Research-Group/Orientation-analysis/blob/master/try1/main.py)  
分词、向量化都写好了。  
文件放在了try1文件夹里。
就是训练时
`clf.fit(X,y)`这句一直报错`ValueError: setting an array element with a sequence.`  
。。。。。。。。。。。。。
。。。。。。。。。。。。。

**Comment by tootal** [comment]
[尝试弄了一下](https://github.com/Goldbach-Research-Group/Orientation-analysis/blob/master/try1/main.py)  
分词、向量化都写好了。  
文件放在了try1文件夹里。
就是训练时
`clf.fit(X,y)`这句一直报错`ValueError: setting an array element with a sequence.`  
。。。。。。。。。。。。。
。。。。。。。。。。。。。

**Comment by sg-first** [comment]
最后`fit_transform`时用的`x`没有按照它的要求把句子都处理成里面的词都是空格分隔的形式。详参处理的例子`vec.py`中的`getCountVec`（可直接调用）

**Comment by sg-first** [comment]
Geng1234已完成
